# Generated by Django 3.1.2 on 2020-11-02 21:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('get_handling', '0002_long_and_short_newfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='long_and_short',
            name='created',
        ),
        migrations.RemoveField(
            model_name='long_and_short',
            name='newfield',
        ),
    ]
