# Generated by Django 3.1.2 on 2020-11-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('get_handling', '0003_auto_20201103_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='long_and_short',
            name='long_url',
            field=models.CharField(max_length=500),
        ),
    ]
