# Generated by Django 3.1.2 on 2020-11-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('get_handling', '0004_auto_20201103_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='long_and_short',
            name='shortform',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
